### ISSUE TITLE
Feat: solvedAC 연동, allen API를 통해 코테 문제 추천받는 기능 구현

### ISSUE THREAD

**Issue by ARaZoAnna** [high-five-ormi/Algoy-AI#104]
## TODO
  - [x] 8081(Web)으로 부터 user 정보 받는다
  - [x] user 정보를 기반으로 solvedAC api를 통해 user 가 푼 문제 중 상위100문제를 받아온다.
  - [x] Json 형태를 Gson을 이용하여 파싱한다. 문제의 제목을 가져와서 String으로 변환한다.
  - [x] 문제의 제목을 기반하여 allen AI에게 api로 문제 추천을 받는다
  - [x] 답변을 8081(Web)에 리턴한다
  - [x] 로컬에서 테스트

## 설명
api 호출 로직을 모두 8082(AI) 단에서 구현하였습니다
추후 추가 개발:
문제 제목이 아니라 문제id(번호)로 추천 받는 쪽으로 개발하겠습니다.(제목은 너무 기니까요) 
답변은 간결하게 받는게 좋을 것 같습니다.
