### ISSUE TITLE
Test: 챗봇 테스트 코드 작성하기

### ISSUE THREAD

**Issue by JEESW** [high-five-ormi/Algoy-AI#107]
## TODO
  - [x] 챗봇 컨트롤러 단위 테스트 코드 작성 (5개 이상)
  - [x] 챗봇 서비스 단위 테스트 코드 작성 (5개 이상)
  - [x] 챗봇 레파지토리 단위 테스트 코드 작성 (5개 이상)

## 설명
챗봇 기능의 단위 테스트가 필요함.
