### ISSUE TITLE
Bug: 배포 test

### ISSUE THREAD

**Issue by ARaZoAnna** [high-five-ormi/Algoy-AI#127]
## TODO
  - [x] 8081이 배포가 되지 않음
  - [x] 두 애플리케이션의 pid 삭제
  - [x] 서버 내에서 빌드를 통해 코드 체크
  - [x] 재배포 해보기

## 설명
갑자기 배포가 되지 않아서 버그 잡으로 갑니다
