### ISSUE TITLE
Chore: Redis 관련 종속성 및 설정 삭제

### ISSUE THREAD

**Issue by JEESW** [high-five-ormi/Algoy-AI#38]
## TODO
  - [x] build.gradle redis 종속성 삭제
  - [x] yml에서 redis 삭제
  - [x] yml에서 mongoDB 부분을 uri로 변경

## 설명
redis를 사용하지 않기 때문에 관련 설정을 삭제해야합니다. 추가적으로 mongoDB는 uri 방식으로 한줄로 나타내는게 좋을 것 같습니다.
