### ISSUE TITLE
Feature: Web Socket을 이용한 AI 기능 확인용 채팅 구현

### ISSUE THREAD

**Issue by JEESW** [high-five-ormi/Algoy-AI#40]
## TODO
  - [x] WebSocket Config 구현
  - [x] Chat Message Entity 구현
  - [x] Controller, Service, Repostiory 구현
  - [x] Dto 구현
  - [x] html/css/js 구현
  
## 설명
Alan AI API와 어떻게 작동할지 테스트를 위한 채팅 기능을 웹 소켓으로 구현해보았습니다.
