### ISSUE TITLE
Design: 챗봇 SSE 방식에서 마지막 응답만 받게하기 및 마크다운 양식 사용하기

### ISSUE THREAD

**Issue by JEESW** [high-five-ormi/Algoy-AI#65]
## TODO
  - [x] 챗봇 마지막 응답만 받게하기
  - [x] 가볍게 CSS 적용하기
  - [x] 마크다운 양식 사용하기
  - [x] html, css, js 분리하기

## 설명
API 동작 확인을 위한 챗봇이었지만 일단 SSE 방식으로 바로 사용할 수도 있게 만들어 보겠습니다!
