### ISSUE TITLE
Chore: 환경 변수 추가

### ISSUE THREAD

**Issue by JEESW** [high-five-ormi/Algoy-AI#84]
## TODO
  - [x] application.yml에 Web 서버의 ip와 포트 url을 환경 변수로 추가
  - [x] 깃허브 액션 ci/cd에 환경 변수 WEB_IP 추가
  - [x] WebConfig에서 Value로 url 받아오게 변경
